### ISSUE TITLE
gmoccapy: wrong unit in gremlin DRO when machine units are inch

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#1997]
When starting gmoccapy with 
```
LINEAR_UNITS = inch
```
and 
```
RS274NGC_STARTUP_CODE = G20
```
the DRO in gremlin shows mm. Switching to G21 and then back to G20 makes the correct unit in the gremin DRO appear.

See: https://forum.linuxcnc.org/gmoccapy/46799-preview-in-mm-while-dro-s-are-in-inch#251168

**Comment by gmoccapy** [comment]
I am not able to reproduce this behavior, it has been solved somehow.
I close this issue, if the problem does occur again, it may be reopened

**Comment by hansu** [comment]
Did you try with 2.8?

**Comment by hansu** [comment]
Yes, in 2.8.4 this issue is still present, not in 2.9:

![issue1997_Linuxcnc2 8 4](https://github.com/LinuxCNC/linuxcnc/assets/67957916/a152b20b-ec26-4170-ab4b-00ddcb86bbdb)

**Comment by gmoccapy** [comment]
This is solved, I do not know who fixed this issue, but i is solved.

**Comment by hansu** [comment]
I tried with the latest commit on the 2.8 branch...

**Comment by gmoccapy** [comment]
@hansu ; I do not have any computer here in Stuttgart supporting Python2, to check this issue.
If it still poersist, please reopen and fix. 

Should be only comparing both gmoccapy files from 2.8 and 2.9

Norbert
