### ISSUE TITLE
Should machine translation to Russian be reverted?

### ISSUE THREAD

**Issue by petterreinholdtsen** [LinuxCNC/linuxcnc#2667]
Feedback in pull request https://github.com/LinuxCNC/linuxcnc/pull/2653 from Weblate report that Russian translations done by @gfghjjk (https://hosted.weblate.org/user/xXx/#changes) for Russian translation should be reverted, because they are machine-translated, and replace correct translations without understanding the terminology or context.

I do not understand Russian myself, and hope @IlyaKw and @dsa-t can work together with @gfghjji to figure out what to do with the Russian translation strings.

What should be done?  Complete revert and blocking user on Weblate might be alternatives.  I could not find the user on Weblate when checking out how to block, wonder if the user might be blocked on Weblate already.

**Comment by petterreinholdtsen** [comment]
I decided to block xXx from contributing to LinuxCNC translations on
Weblate until I get a reply to my emails from him, to avoid making any revertion task any
larger.

I see IlyaKw has been updating at least some of the translations done by
xXx, no idea if it made it better or worse, but hope for the latter.  I
suspect this mean it is easier to update than to revert moving forward.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I believe the complete set last touched by xXx can be shown using https://hosted.weblate.org/search/linuxcnc/-/ru/?q=state%3A%3E%3Dtranslated+changed_by%3AxXx

**Comment by andypugh** [comment]
Where do you think we are with this?

Actually, how does one access the Russian docs? 
http://linuxcnc.org/docs/stable/html/
Has links only for es, cn and fr.

**Comment by petterreinholdtsen** [comment]
[Andy Pugh]
> Where do you think we are with this?

Last I heard on IRC, IlyaKw was going to have a look at the translations
done by xXx and correct the ones with errors.  Not sure how far he got
with it.

> Actually, how does one access the Russian docs? 
> http://linuxcnc.org/docs/stable/html/
> Has links only for es, cn and fr.

See <URL: http://linuxcnc.org/docs/devel/html/ >, the Weblate updates
are only in the master branch.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by IlyaKw** [comment]
I fixed the errors, this problem no longer exists.

**Comment by andypugh** [comment]
> I fixed the errors, this problem no longer exists.

Thanks

**Comment by petterreinholdtsen** [comment]
[IlyaKw]
> I fixed the errors, this problem no longer exists.

Very good.  The Weblate link with the translations xXx was the last to
touch still show 22 pages.  I assume this mean the translations on these
22 pages are all good.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by IlyaKw** [comment]
The contents of these lines are now correct

**Comment by safeaegis** [comment]
russia is a terrorists state

**Comment by IlyaKw** [comment]
[safeaegis]

Why are you writing this here?? For what ?

**Comment by petterreinholdtsen** [comment]
[IlyaKw]
> The contents of these lines are now correct

Thank you very much for the help.  I guess it is time to close this
ticket. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by safeaegis** [comment]
russia is a terrorist country.
Any technical development on its territory is used to manufacture weapons and kill civilians in Ukraine. I will be grateful if the technical support of terrorists is stopped.
Even if it saves one innocent life, it will be worth it!
PS, I'm sorry that my last comment was not so detailed and you didn't fully understand it last time.
Sincerely, Mykhailo
