### ISSUE TITLE
Many formatting errors after man page conversion to adoc

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#3032]
Since https://github.com/LinuxCNC/linuxcnc/pull/1376 (which makes the man pages being generated from adoc sources, wich is a great improvement!) 
some of them have not ben converted correctly.
**So please do not update the man pages until they are fixed.**

TODO

- [x] man1 pages a-h
- [ ] man1 pages i-z
- [ ] man3 pages
- [x] man9 pages

Here is a list of the differences of the man9 man pages:

![diff_man9](https://github.com/user-attachments/assets/7f53b664-588c-490a-920c-35b8b9a2dec4)

It's mostly when bold formatting is involved:

![diff_classicladder](https://github.com/user-attachments/assets/f39d54bb-496d-44bb-b860-4f301def58a5)

![diff_classicladder 9](https://github.com/user-attachments/assets/2a382a38-a240-48e7-beea-25db27a9f1dd)

Unfortunately due to https://github.com/LinuxCNC/linuxcnc/issues/3031 it is currently not possible to inspect the new generated man pages on the web site. You only can check this on a local build.

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> It's mostly when bold formatting is involved:

While some bold formatting were removed intentionally, the
classicladder.9 ones you show seem to be unintentintional.

I could have spend more time comparing the before and after versions,
but we wanted to complete the migration before the LinuxCNC developer
gathering were over and decided to fix any required cleanup
afterwords.  Very glad to see you are able to assist in tracking down
any problems. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by hansu** [comment]
The problem are strings composed of `<bold><italic>[<bold>]<regular>`
For example
**classicladder.0.in-**_NN_ IN bit::
should be 
`**classicladder.0.in-**_NN_ IN bit::`
but was converted like this
`*classicladder.0.in-*_NN_ IN bit::`

Also some asteriskes appeared before the double colon 

See here the fix for the first man pages: https://github.com/LinuxCNC/linuxcnc/pull/3045/files

@petterreinholdtsen  maybe we can fix this by applying an intelligent regular expression on it?

**Comment by hansu** [comment]
See https://asciidoc-py.github.io/userguide.html#_unconstrained_quotes

**Comment by petterreinholdtsen** [comment]
[Hans Unzner]
> @petterreinholdtsen  maybe we can fix this by applying an intelligent
> regular expression on it?

Feel free to try.  I used pandoc to do the conversion, and hoped it
would do a good enough job.  :)

**Comment by hansu** [comment]
>Feel free to try.  

I was hoping you can help with your expertise ;-)

>I used pandoc to do the conversion, and hoped it
would do a good enough job.  :)

It seems that pandoc has some problems with the inline formatting. Maybe you can report that?

**Comment by hansu** [comment]
@petterreinholdtsen  I have now fixed a few man pages and I think you could also fix some.

Otherwise I tend to revert the converted man pages because the goal was to simplify the maintenance of the man pages and not to introduce a huge amount of work to fix the errorneous converted man pages.

**Comment by andypugh** [comment]
Is this fixed now? 
http://linuxcnc.org/docs/stable/html/man/man9/classicladder.9.html 
Looks OK to me.

**Comment by hansu** [comment]
50% of the man9 pages are fine (double checked), the rest probably as well.

But you can't check it this way unfortunately because of https://github.com/LinuxCNC/linuxcnc/issues/3031

**Comment by smoe** [comment]
I think we are mostly stuck with the man pages PRs of mine still failing on sid.

**Comment by andypugh** [comment]
#3031 is showing as closed now?

**Comment by hansu** [comment]
Yes, the docs are up to date on the website :tada:

**Comment by andypugh** [comment]
So, what needs to be done to close this issue?

**Comment by hansu** [comment]
Spent some hours in manually comparing man pages before and after # 1376.
I will have some several hours train journeys end of october, maybe I have then time to face this.

**Comment by hansu** [comment]
I don't know how to give an AI two lists of files....
I could imagine that an intelligent or AI based diff tool would work.
